### ISSUE TITLE
installation path outdated?

### ISSUE THREAD

**Issue by rawdlite** [kellerkinderDE/K10rDeployment#7]
Documentation states to

> clone this repository into your engine/Shopware/Plugins/Local/Core/

i found i need to clone into custom/plugins to make
`bin/console sw:plugin:reinstall K10rDeployment`
work.

This is shopware 5.3.7

cheers
tom

**Comment by kleinmann** [comment]
This plugin still uses the "old-style" plugin system from before Shopware 5.2. It should not be possible to use this plugin from `custom/plugins`, as far as I can tell. Maybe you were missing a `bin/console sw:plugin:refresh` and only after doing that (maybe via the plugin manager in the backend) the plugin showed up and could be installed? :-)

**Comment by rawdlite** [comment]
Yeah, must have been smth. like this.
I find this Plugin now in ./Plugins/Local/Core/K10rDeployment after doing an deployment.
Issue can be closed.
