### ISSUE TITLE
\Shopware::VERSION not available

### ISSUE THREAD

**Issue by Laemmi** [kellerkinderDE/K10rDeployment#9]
In command "K10rUpdateNeededCommand" the constant "\Shopware::VERSION" not available. I think since Showare version 5.6
My idea:

```
        if ($this->getContainer()->hasParameter('shopware.release.version')) {
            $currentVersion = $this->getContainer()->getParameter('shopware.release.version');
        } else {
            $currentVersion = \Shopware::VERSION;
        }
```

**Comment by sobyte** [comment]
Thank you for this issue @Laemmi

We've fixed this with version 1.3.0 which was released at the moment
